spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/demo?characterEncoding=utf8&useConfigs=maxPerformance&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
    username: user
    password: password